#!/usr/bin/env python
# -*- coding: utf-8 -*-

print "--------输出从1加到100的结果--------"
total = 0
for i in range(1,101):
    total += i
print total

print "--------打印100以内质数--------"
def judge(x):
    for i in range(2,x):
	    if x % i == 0:
		    return False
		return True
